vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       logo_user:
           uri_prefix: '%logos_images%'
           upload_destination: '%kernel.project_dir%/public%logos_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true